include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "lab06")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quadratic equation solver and printing library")
set(CPACK_PACKAGE_CONTACT "leikmadu@users.noreply.github.com")
set(CPACK_PACKAGE_VENDOR "Leikmadu")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.rtf)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# WIX (Windows) настройки
set(CPACK_WIX_UPGRADE_GUID "7C3BEE0F-4437-4C49-8F53-4B87922BEE4B")
set(CPACK_WIX_LICENSE_RTF ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.rtf)

# DEB пакет
set(CPACK_DEBIAN_PACKAGE_NAME "solver")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Quadratic equation solver")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT})

# RPM пакет
set(CPACK_RPM_PACKAGE_NAME "solver")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")

# Базовые генераторы
set(CPACK_GENERATOR "TGZ;ZIP")

include(CPack)
